"""empty message

Revision ID: 00af960a4635
Revises: 6101e0ad54e0
Create Date: 2021-01-20 09:57:36.366977

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '00af960a4635'
down_revision = '6101e0ad54e0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'users', ['nome'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    # ### end Alembic commands ###
