"""empty message

Revision ID: 27be86ffbf0c
Revises: fdfc057300d6
Create Date: 2021-01-22 11:51:28.192953

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '27be86ffbf0c'
down_revision = 'fdfc057300d6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'produtos', 'referencia', ['referencia'], ['id'])
    op.create_foreign_key(None, 'produtos', 'tipo', ['tipo'], ['id'])
    op.create_foreign_key(None, 'produtos', 'fabricante', ['fabricante'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'produtos', type_='foreignkey')
    op.drop_constraint(None, 'produtos', type_='foreignkey')
    op.drop_constraint(None, 'produtos', type_='foreignkey')
    # ### end Alembic commands ###
